replicaCount: 5

image:
  repository: andreyn95/neoflex-k8slab
  tag: latest
  pullPolicy: Always
  pullSecret: dockerhub-secret

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30081
